/**
 * Demo seed data for local dev only. Tiny, hand-written. M8 will replace this
 * with the real nanobanana-website 2380 prompt migration.
 */
export const DEMO_CATEGORIES = [
  { slug: "landscape", nameZh: "风景", nameEn: "Landscape", order: 1 },
  { slug: "portrait", nameZh: "人物", nameEn: "Portrait", order: 2 },
  { slug: "anime", nameZh: "二次元", nameEn: "Anime", order: 3 },
  { slug: "guofeng", nameZh: "国风", nameEn: "Chinese Style", order: 4 },
  { slug: "animal", nameZh: "动物", nameEn: "Animal", order: 5 },
  { slug: "architecture", nameZh: "建筑", nameEn: "Architecture", order: 6 },
];

export const DEMO_TAGS = [
  { slug: "cyberpunk", nameZh: "赛博朋克", nameEn: "Cyberpunk" },
  { slug: "neon", nameZh: "霓虹", nameEn: "Neon" },
  { slug: "minimal", nameZh: "极简", nameEn: "Minimal" },
  { slug: "film", nameZh: "胶片", nameEn: "Film" },
  { slug: "night", nameZh: "夜景", nameEn: "Night" },
  { slug: "rain", nameZh: "雨", nameEn: "Rain" },
  { slug: "purple", nameZh: "紫调", nameEn: "Purple" },
  { slug: "nature", nameZh: "自然", nameEn: "Nature" },
];

export const DEMO_R2_ACCOUNT = {
  name: "Local Dev Placeholder",
  accountId: "dev-account",
  accessKeyId: "dev-key-id",
  // Plaintext placeholder ONLY for dev seed. M4 will switch to AES-GCM-encrypted.
  accessKeySecretEncrypted: "DEV_PLACEHOLDER_NOT_ENCRYPTED",
  bucket: "image-prompts-dev",
  endpoint: "https://placeholder.example.com",
  // Picsum returns a deterministic real photo at https://picsum.photos/seed/{key}/{w}/{h}.
  // Combined with r2_key="seed/{slug}/{w}/{h}" this yields varied dev imagery
  // without any storage backend; the endpoint above remains a placeholder.
  publicUrl: "https://picsum.photos",
  enabled: true,
  priority: 100,
};

export const DEMO_PROMPTS = [
  // ───── Original 6, now with widths/heights ─────
  {
    slug: "cyberpunk-neon-cat",
    titleZh: "赛博朋克霓虹猫",
    titleEn: "Cyberpunk Neon Cat",
    promptZh:
      "一只赛博朋克风格的橘猫,坐在雨夜霓虹招牌下的窗台,毛发被霓虹灯照亮,蓝紫色调,电影级侧逆光,50mm 镜头,浅景深,写实摄影风格",
    promptEn:
      "A cyberpunk-style orange cat sitting on a windowsill under neon signs in a rainy night, fur illuminated by neon lights, blue-purple tones, cinematic side backlighting, 50mm lens, shallow depth of field, photorealistic style",
    negativeZh: "模糊, 噪点, 多余的手",
    negativeEn: "blurry, noisy, extra hands",
    aspectRatio: "16:9",
    categorySlug: "landscape",
    tagSlugs: ["cyberpunk", "neon", "night", "rain"],
    width: 800,
    height: 450,
  },
  {
    slug: "purple-minimal-portrait",
    titleZh: "紫调极简肖像",
    titleEn: "Purple Minimal Portrait",
    promptZh: "极简紫调人物肖像,正面光,纯色背景,胶片质感,柔焦",
    promptEn:
      "Minimal purple-toned portrait, frontal lighting, solid color background, film texture, soft focus",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "portrait",
    tagSlugs: ["purple", "minimal", "film"],
    width: 600,
    height: 800,
  },
  {
    slug: "misty-forest-morning",
    titleZh: "青绿森林晨雾",
    titleEn: "Misty Forest Morning",
    promptZh: "清晨青绿森林中的薄雾,阳光透过树叶形成丁达尔光束,广角",
    promptEn:
      "Misty morning in a green forest, sunlight filtering through leaves as Tyndall beams, wide angle",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "3:2",
    categorySlug: "landscape",
    tagSlugs: ["nature"],
    width: 800,
    height: 600,
  },
  {
    slug: "gobi-sunset-road",
    titleZh: "黄昏戈壁公路",
    titleEn: "Gobi Sunset Road",
    promptZh: "落日下的戈壁公路,远景一辆车,暖橙色调,公路片质感",
    promptEn: "Gobi highway at sunset, a distant car, warm orange tones, road movie aesthetic",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "16:9",
    categorySlug: "landscape",
    tagSlugs: ["film"],
    width: 1280,
    height: 720,
  },
  {
    slug: "rainy-street-deep-grey",
    titleZh: "深灰雨夜街景",
    titleEn: "Rainy Street Deep Grey",
    promptZh: "深灰色调雨夜街景,反光路面,孤独人物背影,电影质感",
    promptEn:
      "Deep grey rainy night street, reflective pavement, lone figure from behind, cinematic",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "16:9",
    categorySlug: "landscape",
    tagSlugs: ["night", "rain", "film"],
    width: 1024,
    height: 640,
  },
  {
    slug: "japanese-zen-garden",
    titleZh: "日式禅院庭院",
    titleEn: "Japanese Zen Garden",
    promptZh: "极简日式禅院庭院,白沙耙痕,枯石,苔藓,黄昏柔光",
    promptEn: "Minimalist Japanese zen garden, raked white sand, dry rocks, moss, soft dusk light",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "3:2",
    categorySlug: "architecture",
    tagSlugs: ["minimal"],
    width: 800,
    height: 600,
  },

  // ───── Landscape additions ─────
  {
    slug: "alpine-lake-mirror",
    titleZh: "高山倒影湖",
    titleEn: "Alpine Mirror Lake",
    promptZh: "清晨高山湖面如镜,远山倒影,薄雾,冷色调,广角",
    promptEn: "Alpine lake glassy at dawn, distant peaks reflected, thin mist, cool tones, wide",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "3:2",
    categorySlug: "landscape",
    tagSlugs: ["nature", "minimal"],
    width: 600,
    height: 400,
  },
  {
    slug: "neon-tokyo-alley",
    titleZh: "霓虹东京小巷",
    titleEn: "Neon Tokyo Alley",
    promptZh: "潮湿的东京小巷,霓虹招牌密布,蒸汽,夜雨,赛博朋克氛围",
    promptEn: "Damp Tokyo alley packed with neon signs, steam, night rain, cyberpunk mood",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "landscape",
    tagSlugs: ["cyberpunk", "neon", "rain", "night"],
    width: 600,
    height: 900,
  },
  {
    slug: "iceland-volcanic-coast",
    titleZh: "冰岛火山海岸",
    titleEn: "Iceland Volcanic Coast",
    promptZh: "冰岛黑沙海岸,远处火山轮廓,极光余晖,冷色调",
    promptEn: "Icelandic black sand coast, volcano silhouette, fading aurora, cool palette",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "16:9",
    categorySlug: "landscape",
    tagSlugs: ["nature", "night"],
    width: 1200,
    height: 600,
  },
  {
    slug: "desert-dune-noon",
    titleZh: "正午沙丘",
    titleEn: "Desert Dunes at Noon",
    promptZh: "正午沙丘的曲线与阴影对比,极简构图,暖橙色调",
    promptEn: "Curves and shadows of desert dunes at noon, minimal composition, warm orange",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "1:1",
    categorySlug: "landscape",
    tagSlugs: ["minimal", "nature"],
    width: 600,
    height: 600,
  },
  {
    slug: "norwegian-fjord-fog",
    titleZh: "挪威峡湾迷雾",
    titleEn: "Norwegian Fjord Fog",
    promptZh: "挪威峡湾中漂浮的浓雾,孤独小船,胶片质感",
    promptEn: "Heavy fog rolling through a Norwegian fjord, lone boat, film texture",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "3:2",
    categorySlug: "landscape",
    tagSlugs: ["film", "nature"],
    width: 700,
    height: 500,
  },
  {
    slug: "highway-purple-twilight",
    titleZh: "紫调高速暮色",
    titleEn: "Highway Purple Twilight",
    promptZh: "无尽公路通向紫调暮色,合成波美学,长曝光",
    promptEn: "Endless highway into a purple twilight, synthwave aesthetic, long exposure",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "16:9",
    categorySlug: "landscape",
    tagSlugs: ["purple", "neon", "film"],
    width: 1200,
    height: 600,
  },

  // ───── Portrait additions ─────
  {
    slug: "film-noir-woman",
    titleZh: "黑色电影女子",
    titleEn: "Film Noir Woman",
    promptZh: "黑白胶片肖像,百叶窗光影投射,30年代造型",
    promptEn: "Black-and-white film portrait, venetian blind light, 1930s styling",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "portrait",
    tagSlugs: ["film", "night"],
    width: 500,
    height: 750,
  },
  {
    slug: "studio-strobe-redhead",
    titleZh: "影棚红发肖像",
    titleEn: "Studio Strobe Redhead",
    promptZh: "影棚硬光红发女子肖像,黑色背景,皮肤质感细腻",
    promptEn: "Studio hard-light portrait of a redhead, black backdrop, fine skin texture",
    negativeZh: "塑料感, 过度磨皮",
    negativeEn: "plastic skin, over-smoothed",
    aspectRatio: "2:3",
    categorySlug: "portrait",
    tagSlugs: ["minimal"],
    width: 400,
    height: 600,
  },
  {
    slug: "rainy-window-portrait",
    titleZh: "雨窗少年",
    titleEn: "Rainy Window Portrait",
    promptZh: "少年靠在被雨水模糊的窗前,自然光,蓝色调",
    promptEn: "Boy leaning on a rain-blurred window, natural light, blue tones",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "1:1",
    categorySlug: "portrait",
    tagSlugs: ["rain", "film"],
    width: 600,
    height: 600,
  },
  {
    slug: "neon-tinted-dancer",
    titleZh: "霓虹舞者",
    titleEn: "Neon-Tinted Dancer",
    promptZh: "霓虹灯下的舞者剪影,运动模糊,紫粉双色光",
    promptEn: "Silhouette of a dancer in neon, motion blur, magenta-cyan dual light",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "portrait",
    tagSlugs: ["neon", "purple", "night"],
    width: 600,
    height: 900,
  },

  // ───── Anime additions ─────
  {
    slug: "anime-rooftop-sunset",
    titleZh: "二次元天台黄昏",
    titleEn: "Anime Rooftop Sunset",
    promptZh: "二次元少女在天台远望,夕阳橘红,新海诚风,云层细致",
    promptEn:
      "Anime girl gazing from a rooftop at sunset, Makoto Shinkai style, finely detailed clouds",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "16:9",
    categorySlug: "anime",
    tagSlugs: ["film"],
    width: 800,
    height: 450,
  },
  {
    slug: "anime-mecha-skyline",
    titleZh: "机甲都市天际线",
    titleEn: "Anime Mecha Skyline",
    promptZh: "巨型机甲俯瞰未来都市,日系动画线条,落日辉光",
    promptEn: "Giant mecha overlooking a future city, anime line work, sunset glow",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "anime",
    tagSlugs: ["cyberpunk", "neon"],
    width: 600,
    height: 900,
  },
  {
    slug: "anime-cafe-window",
    titleZh: "咖啡馆窗边少女",
    titleEn: "Anime Cafe Window Girl",
    promptZh: "动画风格少女在咖啡馆窗边,雨夜霓虹倒影,温暖灯光",
    promptEn:
      "Anime-style girl by a cafe window, neon reflections on rainy night, warm interior light",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "1:1",
    categorySlug: "anime",
    tagSlugs: ["rain", "neon", "night"],
    width: 800,
    height: 800,
  },
  {
    slug: "anime-fox-spirit-forest",
    titleZh: "森林狐妖",
    titleEn: "Anime Fox Spirit Forest",
    promptZh: "九尾狐妖少女漫步竹林,飘落樱花,柔和水彩动画风",
    promptEn:
      "Nine-tailed fox spirit girl walking through bamboo, falling petals, soft watercolor anime",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "anime",
    tagSlugs: ["nature", "purple"],
    width: 600,
    height: 900,
  },

  // ───── Guofeng additions ─────
  {
    slug: "guofeng-misty-mountain-ink",
    titleZh: "水墨远山",
    titleEn: "Guofeng Misty Mountain Ink",
    promptZh: "宋代水墨山水,远山近松,留白意境",
    promptEn: "Song dynasty ink landscape, far mountains and near pines, expressive negative space",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "guofeng",
    tagSlugs: ["minimal", "nature"],
    width: 600,
    height: 900,
  },
  {
    slug: "guofeng-hanfu-portrait",
    titleZh: "汉服仕女",
    titleEn: "Hanfu Portrait",
    promptZh: "唐风仕女汉服肖像,绢丝质感,工笔细节,金箔背景",
    promptEn: "Tang-style hanfu portrait, silk texture, fine brushwork, gold leaf background",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "guofeng",
    tagSlugs: ["minimal"],
    width: 400,
    height: 600,
  },
  {
    slug: "guofeng-lantern-night-river",
    titleZh: "灯笼夜河",
    titleEn: "Guofeng Lantern Night River",
    promptZh: "古镇夜河灯笼飘浮,水面倒影,暖橙色调",
    promptEn: "Old-town river at night with floating lanterns, water reflections, warm orange",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "16:9",
    categorySlug: "guofeng",
    tagSlugs: ["night", "film"],
    width: 1200,
    height: 600,
  },
  {
    slug: "guofeng-crane-pine",
    titleZh: "松鹤延年",
    titleEn: "Crane and Pine",
    promptZh: "古典工笔画白鹤栖于松枝,薄雾,淡彩",
    promptEn: "Classical gongbi painting, white crane perched on pine, mist, pale palette",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "1:1",
    categorySlug: "guofeng",
    tagSlugs: ["minimal", "nature"],
    width: 600,
    height: 600,
  },

  // ───── Animal additions ─────
  {
    slug: "snow-fox-blizzard",
    titleZh: "暴雪雪狐",
    titleEn: "Snow Fox in Blizzard",
    promptZh: "雪狐在暴风雪中漫步,细致毛发,冷色调,景深浅",
    promptEn: "Arctic fox walking through a blizzard, fine fur detail, cool palette, shallow DOF",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "3:2",
    categorySlug: "animal",
    tagSlugs: ["nature", "minimal"],
    width: 600,
    height: 400,
  },
  {
    slug: "tiger-portrait-low-key",
    titleZh: "低调老虎肖像",
    titleEn: "Tiger Low-Key Portrait",
    promptZh: "低调照明下老虎肖像,深黑背景,毛发与眼神锐利",
    promptEn: "Low-key lit tiger portrait, deep black background, sharp fur and gaze",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "animal",
    tagSlugs: ["film", "night"],
    width: 500,
    height: 750,
  },
  {
    slug: "hummingbird-macro",
    titleZh: "蜂鸟微距",
    titleEn: "Hummingbird Macro",
    promptZh: "蜂鸟悬停采蜜的微距摄影,翅膀运动模糊,1/8000s",
    promptEn: "Macro hummingbird hovering at a flower, wing motion blur, 1/8000s",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "1:1",
    categorySlug: "animal",
    tagSlugs: ["nature"],
    width: 600,
    height: 600,
  },
  {
    slug: "wolf-pack-moonlight",
    titleZh: "月光狼群",
    titleEn: "Wolf Pack Moonlight",
    promptZh: "雪原狼群在满月下嚎叫,蓝色月光,电影质感",
    promptEn: "Wolf pack howling on a snowy plain under full moon, blue moonlight, cinematic",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "16:9",
    categorySlug: "animal",
    tagSlugs: ["night", "film", "nature"],
    width: 1024,
    height: 640,
  },

  // ───── Architecture additions ─────
  {
    slug: "brutalist-concrete-stair",
    titleZh: "粗野主义混凝土楼梯",
    titleEn: "Brutalist Concrete Stair",
    promptZh: "粗野主义混凝土螺旋楼梯,顶光斜射,极简对比",
    promptEn: "Brutalist concrete spiral staircase, top-down light, minimal contrast",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "2:3",
    categorySlug: "architecture",
    tagSlugs: ["minimal"],
    width: 600,
    height: 1200,
  },
  {
    slug: "shanghai-skyline-blue-hour",
    titleZh: "蓝色时刻上海天际线",
    titleEn: "Shanghai Skyline Blue Hour",
    promptZh: "蓝色时刻的上海天际线,陆家嘴灯火,长曝光,水面倒影",
    promptEn: "Shanghai skyline at blue hour, Lujiazui lights, long exposure, river reflection",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "16:9",
    categorySlug: "architecture",
    tagSlugs: ["neon", "night"],
    width: 1200,
    height: 600,
  },
  {
    slug: "moroccan-tile-courtyard",
    titleZh: "摩洛哥瓷砖庭院",
    titleEn: "Moroccan Tile Courtyard",
    promptZh: "摩洛哥彩色瓷砖庭院,午后斜光,几何对称",
    promptEn: "Moroccan colorful tiled courtyard, afternoon raking light, geometric symmetry",
    negativeZh: undefined,
    negativeEn: undefined,
    aspectRatio: "1:1",
    categorySlug: "architecture",
    tagSlugs: ["minimal"],
    width: 800,
    height: 800,
  },
];

export const DEMO_SITE_SETTINGS = [
  // -- submit.* — consumed by getSubmitConfig() in apps/api/src/lib/submit-config.ts (Task 5)
  { key: "submit.daily_limit", value: 10, description: "Per-user daily submission limit (good standing)" },
  { key: "submit.demoted_daily_limit", value: 5, description: "Per-user daily limit when rejectedCount >= demote_threshold" },
  { key: "submit.demote_threshold", value: 3, description: "rejectedCount >= this triggers halved daily limit" },
  { key: "submit.guidelines_version", value: 1, description: "Current community guidelines version (bumping invalidates user accept)" },
  { key: "submit.max_images_per_submission", value: 5, description: "Max image files per single submission" },
  { key: "submit.min_images_per_submission", value: 1, description: "Min image files per single submission" },
  { key: "submit.max_image_size_bytes", value: 10485760, description: "Max bytes per uploaded image (10 MB)" },
  {
    key: "submit.allowed_mime",
    value: ["image/jpeg", "image/png", "image/webp"],
    description: "Allowed image MIME types",
  },
  { key: "submit.max_tags", value: 6, description: "Max tags per prompt" },
  { key: "submit.presign_ttl_seconds", value: 900, description: "Presigned upload URL TTL (seconds)" },
  { key: "submit.reject_reason_min_chars", value: 1, description: "Min chars in admin rejection reason" },
  { key: "submit.reject_reason_max_chars", value: 500, description: "Max chars in admin rejection reason" },
  { key: "submit.daily_reset_timezone", value: "Asia/Shanghai", description: "Timezone for the daily-limit reset boundary" },

  // -- community_guidelines.* — body shown to submitters before they may submit
  { key: "community_guidelines.body",
    value: { zh: "请遵守社区准则。", en: "Please follow community guidelines." },
    description: "Guidelines body (bilingual)" },

  // -- view_count.* — interaction dedup window
  { key: "view_count.dedup_hours", value: 24, description: "View dedup window in hours" },

  // -- translator.* — M10a seeds keys; M10b wires the endpoint + UI
  { key: "translator.enabled", value: false, description: "AI translation feature toggle (off until M10b)" },
  { key: "translator.base_url", value: "https://api.openai.com/v1", description: "OpenAI /responses-compatible endpoint base URL (relay-friendly)" },
  { key: "translator.api_key", value: "", description: "API key (encrypted at REST when set via owner UI)" },
  { key: "translator.model", value: "gpt-4o-mini", description: "Model name passed to /responses" },
  { key: "translator.system_prompt", value: "", description: "Override built-in fallback prompt (empty = code default)" },
  { key: "translator.max_chars_per_request", value: 2000, description: "Max input chars per single translate call" },
  { key: "translator.rate_limit_per_user_hour", value: 20, description: "Max translate calls per user per hour" },

  // -- site.* — misc site-wide
  { key: "site.maintenance_mode", value: false, description: "Show maintenance banner / block writes when true" },
  { key: "site.maintenance_message", value: "", description: "Message displayed during maintenance" },
];
